---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: sealed-secrets
  namespace: adm
spec:
  chartGitPath: sealed-secrets
  releaseName: sealed-secrets
  values:
    image: quay.io/bitnami/sealed-secrets-controller:v0.7.0
