---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:soufianem370/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: soufianem370/podinfo
      tag: dev-5hfdy7mc
    replicaCount: 1
    hpa:
      enabled: false
    service:
      type: LoadBalancer
      port: 9898

