---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:A-Gordon/helm-operator-get-started
    path: charts/podinfo
    ref: dev
  values:
    image:
      repository: agordon/podinfo
      tag: dev-uzkmsj7p
    replicaCount: 1
    hpa:
      enabled: false

