FROM golang:1.13 as builder

ARG VERSION=unknown
ARG GITCOMMIT=unknown

RUN mkdir -p /podinfo/

WORKDIR /podinfo

ADD https://github.com/stefanprodan/podinfo/archive/3.1.5.tar.gz .

RUN tar xzf 3.1.5.tar.gz --strip 1

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags "-s -w \
  -X github.com/stefanprodan/podinfo/pkg/version.GITCOMMIT=${GITCOMMIT} \
  -X github.com/stefanprodan/podinfo/pkg/version.VERSION=${VERSION}" \
  -a -o bin/podinfo cmd/podinfo/*

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags "-s -w \
  -X github.com/stefanprodan/podinfo/pkg/version.GITCOMMIT=${GITCOMMIT} \
  -X github.com/stefanprodan/podinfo/pkg/version.VERSION=${VERSION}" \
  -a -o bin/podcli cmd/podcli/*

FROM alpine:3.10

RUN addgroup -S app \
    && adduser -S -g app app \
    && apk --no-cache add \
    curl openssl netcat-openbsd

WORKDIR /home/app

COPY --from=builder /podinfo/bin/podinfo .
COPY --from=builder /podinfo/bin/podcli /usr/local/bin/podcli
COPY --from=builder /podinfo/ui ./ui
RUN chown -R app:app ./

USER app

CMD ["./podinfo"]