---
apiVersion: helm.integrations.flux.weave.works/v1alpha
kind: FluxHelmRelease
metadata:
  name: database
  namespace: test
  labels:
    chart: mongodb
spec:
  chartGitPath: mongodb
  releaseName: database
  values:
    image: bitnami/mongodb:3.7.1-r0
    serviceType: ClusterIP
    persistence:
      enabled: false
      accessMode: ReadWriteOnce
      size: 8Gi
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
    nodeSelector: {}
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1

