---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: frontend
  namespace: test
  labels:
    chart: podinfo
spec:
  chartGitPath: podinfo
  releaseName: frontend
  values:
    replicaCount: 1
    backend: http://backend-podinfo:9898/echo
    image:
      tag: 0.2.2
    service:
      type: NodePort
      nodePort: 31198
